ARG PHP_VERSION
FROM 890731937511.dkr.ecr.eu-west-1.amazonaws.com/boxtal-woocommerce:$PHP_VERSION
ARG PORT

ENV HOME=/home/docker
WORKDIR $HOME
ADD . $HOME
RUN chown -R docker:docker $HOME
RUN chmod 777 $HOME/build/entrypoint.sh
RUN sed -i "s/Listen 80/Listen $PORT/" /etc/apache2/ports.conf
RUN sed -i "s/:80/:$PORT/" /etc/apache2/sites-enabled/000-default.conf

ENTRYPOINT $HOME/build/entrypoint.sh

USER docker
